### ISSUE TITLE
Portrait videos cropped

### ISSUE THREAD

**Issue by jmgirven** [MasayukiSuda/ExoPlayerFilter#1]
Great library! Congrats.

I can see you have thought about different options for fitting the surface inside the parent ([playerScaleType](https://github.com/MasayukiSuda/ExoPlayerFilter/blob/master/epf/src/main/java/com/daasuu/epf/EPlayerView.java#L23)), but probably haven't gotten round to finishing it. So if you put a portrait video into the library it fills the width and therefore crops the top and bottom of the video.

I figure this must be a solved problem somewhere. Would the code from [VideoView](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/widget/VideoView.java#153) not do what you (I) need?

I can just override onMeasure for now, so it isn't a problem.

**Comment by MasayukiSuda** [comment]
Thank you for posting the issue.

I think that it is enough to decide the size by View which wraps EPlayerView. For example, like [MovieWrapperView](https://github.com/MasayukiSuda/ExoPlayerFilter/blob/master/sample/src/main/java/com/daasuu/exoplayerfilter/MovieWrapperView.java).

If it is portrait size video, I assume that you designate portrait with onMeasure of MovieWrapperView.
