### ISSUE TITLE
Change EPlayerView size according to video size

### ISSUE THREAD

**Issue by Tolea86** [MasayukiSuda/ExoPlayerFilter#12]
I have a problem here, need to resize the EPlayerView size to fit in specific size the video leaving left and right part transparent if video is vertical. As for now in your demo video is horizontal and if I put a vertical video it will be put across the whole screen. Is there a way to resize the EPlayerView according to video size?

**Comment by jmgirven** [comment]
I asked a similar question in #1. See [MovieWrapperView](https://github.com/MasayukiSuda/ExoPlayerFilter/blob/master/sample/src/main/java/com/daasuu/exoplayerfilter/MovieWrapperView.java).

**Comment by Tolea86** [comment]
oh yeah sorry for inconvenience
