### ISSUE TITLE
How to save the filtered video?

### ISSUE THREAD

**Issue by AlaaAlShammaa** [MasayukiSuda/ExoPlayerFilter#14]
Hello, Everyone! I was wondering if there is a way to save the video into device storage after applying filters to it?

**Comment by MasayukiSuda** [comment]
Use <a href="https://developer.android.com/reference/android/media/MediaCodec.html">mediaCodec</a>.

**Comment by AlaaAlShammaa** [comment]
How to use media codec and how to get the output stream to pass it to media codec? I couldn't find a method to get the byte array of the playing video!

**Comment by mPixster** [comment]
Hello, anyone found ..how to save filter video in exo player.
