### ISSUE TITLE
亲爱的作者大大  支持加速播放吗？

### ISSUE THREAD

**Issue by ltpostbox** [MasayukiSuda/ExoPlayerFilter#16]
亲爱的作者大大  支持加速播放吗？ @MasayukiSuda

**Comment by MasayukiSuda** [comment]
see <a href="https://github.com/google/ExoPlayer/blob/0e6ef0e/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L180">this</a>.
