### ISSUE TITLE
Unable to open in gradle 2.2.0

### ISSUE THREAD

**Issue by kjanagiram** [MasayukiSuda/ExoPlayerFilter#19]
Unable to open this project in com.android.tools.build:gradle:2.2.0.  Below error is thrown. 

 **Error:Failed to resolve: com.android.support:support-annotations:27.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/home/janakiraman/AndroidStudioProjects/ExoPlayerFilter-master/sample/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>**

**Error:(24, 13) Failed to resolve: com.android.support:appcompat-v7:26.1.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/home/janakiraman/AndroidStudioProjects/ExoPlayerFilter-master/sample/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>**

**Comment by MasayukiSuda** [comment]
not support gradle 2.2.0
