### ISSUE TITLE
I can't use SimpleExoPlayerView after include this library in all over app.!

### ISSUE THREAD

**Issue by emergingcoders2** [MasayukiSuda/ExoPlayerFilter#20]
If I use this library and use SimpleExoPlayerView for simple use for other work then:

java.lang.NoSuchMethodError: No interface method addListener(Lcom/google/android/exoplayer2/ExoPlayer$EventListener;)V in class Lcom/google/android/exoplayer2/ExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.ExoPlayer' appears in /data/app/com.emergingcoders.socio-1/base.apk)

So, I currently forget to use this library!

**Comment by MasayukiSuda** [comment]
Read <a href="https://google.github.io/ExoPlayer/guide.html#getting-started">this</a>.
