### ISSUE TITLE
Using latest exoplayer core version

### ISSUE THREAD

**Issue by idyuzheva** [MasayukiSuda/ExoPlayerFilter#21]
hey,

I'd like to use your lib along with the latest exoplayer version 2.6.1
however in the lib is used version 2.6.0, which makes build fail due to different versions.
It is possible to change lib version to the latest one?
p.s. I've tried it locally, works ok, no additional efforts required.

**Comment by banxxi** [comment]
Did you try excluding exoplayer from the dependency and including 2.6.1 in your project.

**Comment by MasayukiSuda** [comment]
i fixed.
