### ISSUE TITLE
Surface not released

### ISSUE THREAD

**Issue by jmgirven** [MasayukiSuda/ExoPlayerFilter#26]
Should you release the `Surface` you create in [EPlayerRenderer](https://github.com/MasayukiSuda/ExoPlayerFilter/blob/master/epf/src/main/java/com/daasuu/epf/EPlayerRenderer.java#L102) when you finish using the `EPlayerView`? Otherwise you are leaking the `Surface`. You can see this by enabling `StrictMode` and creating and destroying an `Activity` with an `EPlayerView`.

I also notice that you have a `release` method in [ESurfaceTexture](https://github.com/MasayukiSuda/ExoPlayerFilter/blob/master/epf/src/main/java/com/daasuu/epf/ESurfaceTexture.java#L48) that I couldn't see being used. Should that also be called?

**Comment by MasayukiSuda** [comment]
Thanks ! I fixed.
