### ISSUE TITLE
Saving a video after applying filter

### ISSUE THREAD

**Issue by krupinder955** [MasayukiSuda/ExoPlayerFilter#27]
I need to save the video after applying the filter, is there a way i can do it?

**Comment by MasayukiSuda** [comment]
Not support.

**Comment by HardikMaru** [comment]
HI @krupinder955 

I was also working on something like your requirement. After spending few hours I came with solution of using another library named "Mp4Composer-android" by the same author @MasayukiSuda 

So basically what I did is to use ExoPlayerFilter to show the filters on video and when to save I used Mp4Composer. Yes, both library does not have all and same filters, but you can create one for your own OR can be happy 90% of filters which are same on both.

Hope this will help you.
