### ISSUE TITLE
Multiple instances of the playerview not working

### ISSUE THREAD

**Issue by banxxi** [MasayukiSuda/ExoPlayerFilter#3]
Hi I just tried to do multiple instances of the playerview in a viewpager but it didn't work, and I was wondering why do you have any idea?

**Comment by MasayukiSuda** [comment]
Will you paste the code you wrote here?

**Comment by banxxi** [comment]
This is my Fragment Class
`public class FilterItemFragment extends Fragment {
    
    @Inject
    protected SimpleExoPlayer simpleExoPlayer;
    @Inject
    protected DataSource.Factory dataSourceFactory;
    @Inject
    protected ExtractorsFactory extractorsFactory;
    
    private SelectedMedia selectedMedia;
    private MediaSource videoSource;
    EPlayerView ePlayerView;
    MovieWrapperView movieWrapperView;


    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.filter_vp_item, container, false);
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        PlayerComponent playerComponent = DaggerPlayerComponent.builder()
                .playerModule(new PlayerModule(getContext()))
                .build();
        playerComponent.inject(this);
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        movieWrapperView = (MovieWrapperView) getActivity().findViewById(R.id.filter_player);
        ePlayerView = new EPlayerView(getContext());

        ePlayerView.setSimpleExoPlayer(simpleExoPlayer);
        ePlayerView.setLayoutParams(new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        movieWrapperView.addView(ePlayerView);
        ePlayerView.onResume();
        setUrlAndPrepare(Uri.parse(selectedMedia.getPath()));
        ePlayerView.setGlFilter(new GlSepiaFilter());
    }

    private void setUrlAndPrepare(Uri url) {
        videoSource = new ExtractorMediaSource(url,
                dataSourceFactory, extractorsFactory, null, null);
        simpleExoPlayer.prepare(videoSource, true, true);
        simpleExoPlayer.setPlayWhenReady(true);
    }

    public static FilterItemFragment newInstance(SelectedMedia selectedMedia) {

        FilterItemFragment fragment = new FilterItemFragment();
        fragment.selectedMedia = selectedMedia;
        return fragment;
    }
}`

Only the first fragment is working other fragments are all white

**Comment by MasayukiSuda** [comment]
The reason why it does not working is that simpleExoPlayer is a singleton.
Each EPlayerView requires a SimpleExoPlayer instance.
