### ISSUE TITLE
How to change time applying filter 

### ISSUE THREAD

**Issue by cuagia** [MasayukiSuda/ExoPlayerFilter#33]
Assume that I have a 50 seconds video. I want to apply filter only from 20 to 30 second.
How to do that ? Thank you!

**Comment by MasayukiSuda** [comment]
read <a href="https://medium.com/google-exoplayer/variable-speed-playback-with-exoplayer-e6e6a71e0343">this.</a>

**Comment by cuagia** [comment]
You get me wrong, sorry for my poor English. I mean, I don't want to apply filter for whole 50 seconds of video, I just want apply 10 seconds from second 20 to 30.
