### ISSUE TITLE
some device will crash when apply GlMonochromeFilter and GlVignetteFilter,  the way of using glUniform3fv  might be wrong

### ISSUE THREAD

**Issue by shaopx** [MasayukiSuda/ExoPlayerFilter#35]
device: Huawei V8    
android version: 8.0
gl info: 
vendor:Arm     version:OpenGL ES 3.2
renderer:Mali-T880  

the demo will crash when i select GlMonochromeFilter or GlVignetteFilter  . 
after a try , i found out change the following code  will fix crash.

` GLES20.glUniform3fv(getHandle("xxxxx"), 0, vignetteColor, 0);`      ---- will crash
to 
` GLES20.glUniform3fv(getHandle("xxxxx"), 1, vignetteColor, 0);`      ------ this works for me

I'm not good at opengl es, so I'm not sure about this .
any way, could you please check this ?  
thanks for this gorgeous project!

**Comment by MasayukiSuda** [comment]
i fixed . use v0.2.3.
