### ISSUE TITLE
Make videos fit a particular layout

### ISSUE THREAD

**Issue by khurana3192** [MasayukiSuda/ExoPlayerFilter#38]
I am having trouble rendering the video in a way that it fits the layout.
((FrameLayout) findViewById(R.id.videoView3)).addView(ePlayerView);
I have defined a frame layout,  and it takes a particular width and height, however when I add this player in this view, it does not fit, it only stretches till the video height.

I want it to scale to the height and width of the layout.

**Comment by MasayukiSuda** [comment]
a similar question in #1. See [MovieWrapperView](https://github.com/MasayukiSuda/ExoPlayerFilter/blob/master/sample/src/main/java/com/daasuu/exoplayerfilter/MovieWrapperView.java).
