### ISSUE TITLE
How to set bitmap preview for each filter

### ISSUE THREAD

**Issue by TejrajJadhav** [MasayukiSuda/ExoPlayerFilter#43]
![WhatsApp Image 2019-07-31 at 4 19 28 PM](https://user-images.githubusercontent.com/18294716/62207734-877a4a80-b3b2-11e9-85bf-12ac94584d8f.jpeg)
I wants the horizontal recyclerview where i want to set video effects preview bitmap image.
Is this possible. Please help

**Comment by MasayukiSuda** [comment]
not support
