### ISSUE TITLE
Can’t add the library to the project

### ISSUE THREAD

**Issue by P1NG2WIN** [MasayukiSuda/ExoPlayerFilter#45]
When trying to add your library to a project using `    implementation 'com.github.MasayukiSuda:ExoPlayerFilter:v0.2.4'
` I get an error 

> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.MasayukiSuda:ExoPlayerFilter:v0.2.4.

Full text - https://hasteb.in/evuqaruw.sql

Maybe you know the solution?

**Comment by MasayukiSuda** [comment]
## Gradle
Step 1. Add the JitPack repository to your build file
```groovy
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```
Step 2. Add the dependency
```groovy
    dependencies {
        implementation 'com.github.MasayukiSuda:ExoPlayerFilter:v0.2.4'
        implementation 'com.google.android.exoplayer:exoplayer-core:2.10.2'
    }
```
This library depends ExoPlayer core 2.10.2

**Comment by P1NG2WIN** [comment]
@MasayukiSuda Did not help
My full gradle https://hasteb.in/givekeve.gradle  https://hasteb.in/olilulum.gradle
