### ISSUE TITLE
Remove Filter(No Filter) option is not there

### ISSUE THREAD

**Issue by aloklearning** [MasayukiSuda/ExoPlayerFilter#5]
I wan to remove filter with the press of a button and come back to normal. I've searched on this library I couldn't found any thing for removing the filter or coming back to normal. 

Please let me know if there is anything from which I can remove the filter like setting the filters. Thanks.

**Comment by MasayukiSuda** [comment]
```
ePlayerView.setGlFilter(new GlFilter());
```
You can remove the filter like setting the filters.
