### ISSUE TITLE
SimpleExoPlayer: Player is accessed on the wrong thread.

### ISSUE THREAD

**Issue by nbourdin** [MasayukiSuda/ExoPlayerFilter#53]
Hello,
When i launch the sample from branch master I get the following error : 

```

W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1242)
        at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(SimpleExoPlayer.java:321)
        at com.daasuu.epf.EPlayerRenderer.onSurfaceCreated(EPlayerRenderer.java:103)
        at com.daasuu.epf.EFrameBufferObjectRenderer.onSurfaceCreated(EFrameBufferObjectRenderer.java:40)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)

```

Same issue when i try to use the lib in my project.

Any idea ? Thanks in advance

**Comment by yangcheng** [comment]
I have the same issue.

**Comment by ParthP-7** [comment]
I am facing the same issue. Did you find any solution?

**Comment by nbourdin** [comment]
No sorry

**Comment by sebdomdev** [comment]
Seems like something changed in the newer exoplayer library versions. If you **use 2.10.5, it actually works** (that's the version that the sample app is using). I assume it has to do with exo player being accessed from the open gl thread instead of the main thread but I'm not sure.

**Comment by saptan** [comment]
I have the same issue.

**Comment by saptan** [comment]
```
    implementation 'com.google.android.exoplayer:exoplayer-core:2.13.2'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.13.2'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.13.2'
    implementation 'com.google.android.exoplayer:extension-rtmp:2.13.2'
```

**Comment by saptan** [comment]
Need replace this code:
```
        Surface surface = new Surface(previewTexture.getSurfaceTexture());
        this.simpleExoPlayer.setVideoSurface(surface);
```

with:

```
new Handler(Looper.getMainLooper()).post(() -> {
            Surface surface = new Surface(previewTexture.getSurfaceTexture());
            simpleExoPlayer.setVideoSurface(surface);
        });
```

**Comment by yangcheng** [comment]
> Need replace this code:
> 
> ```
>         Surface surface = new Surface(previewTexture.getSurfaceTexture());
>         this.simpleExoPlayer.setVideoSurface(surface);
> ```
> 
> with:
> 
> ```
> new Handler(Looper.getMainLooper()).post(() -> {
>             Surface surface = new Surface(previewTexture.getSurfaceTexture());
>             simpleExoPlayer.setVideoSurface(surface);
>         });
> ```
> 
> https://github.com/MasayukiSuda/ExoPlayerFilter/blob/master/epf/src/main/java/com/daasuu/epf/EPlayerRenderer.java#L102-L103

I added a PR based on the suggestion, https://github.com/MasayukiSuda/ExoPlayerFilter/pull/58

**Comment by MasayukiSuda** [comment]
Fixed.
