### ISSUE TITLE
How to rotate EPlayerView?

### ISSUE THREAD

**Issue by memishood** [MasayukiSuda/ExoPlayerFilter#56]
I want to rotate the video but i couldn't find any method, I have tried rotate the parent layout but it wasn't successful

**Comment by memishood** [comment]
I have solved the problem by adding the following codes to the Renderer Class;
```
@Override
public void onDrawFrame(final EFramebufferObject fbo) {
       ...
       Matrix.scaleM(MVPMatrix, 0, scale[0], scale[1], 1); // fix video stretch using scale
       Matrix.rotateM(MVPMatrix, 0, -angle, 0.f, 0.f, 1.f); // rotate the video
       ....
       previewFilter.draw(texName, MVPMatrix, STMatrix, aspectRatio);
}
```

**Comment by vksBhardwaj** [comment]
@memishood can u help me
I ma creating app with Landscape mode and when i try to show vertical type video. Then it will stretch or not properly view
