### ISSUE TITLE
Save files with the applied filter

### ISSUE THREAD

**Issue by aloklearning** [MasayukiSuda/ExoPlayerFilter#6]
The work is almost done, now I've to save the filtered video in the local storage. I'm searching for a way out to do that. Do we have something to save the video with the applied filter. As when we apply filter to some video. How to do we get the value of the changed video in order to save it in the specified path. 

Thanks

**Comment by MasayukiSuda** [comment]
Use <a href="https://developer.android.com/reference/android/media/MediaCodec.html">mediaCodec</a>.

**Comment by aloklearning** [comment]
Could you please give me some more information as MediaCodec is too big and I'm searching for a way out to save the filtered video only. I've gone through MediaCodec and I'm wondering how to use this in my project in order to save the video. Thanks

**Comment by MasayukiSuda** [comment]
No. because it has nothing to do with this repository.

**Comment by mPixster** [comment]
Hello, anyone found ..how to save filter video in exoplanet

**Comment by MasayukiSuda** [comment]
Use <a href="https://github.com/MasayukiSuda/GPUVideo-android">this</a>.
