### ISSUE TITLE
How to use the Vintage Filter 

### ISSUE THREAD

**Issue by aloklearning** [MasayukiSuda/ExoPlayerFilter#7]
I've used your exoplayerfilter and it is working fine. What I'm looking for is a **vintage filter**, do we have vintage filter? If not then please give some suggestion for some way to inculcate in this filter. Thanks

**Comment by MasayukiSuda** [comment]
see <a href="https://github.com/MasayukiSuda/ExoPlayerFilter/blob/master/sample/src/main/java/com/daasuu/exoplayerfilter/FilterType.java">this</a>
